name: 'GitHub Pages Publish'
description: 'Publish to GitHub pages using your SSH key'
inputs:
  BRANCH:
    description: 'Branch to move'
    required: false
    default: 'gh-pages'
  FOLDER:
    description: 'Folder to move'
    required: true
  SSHKEY:
    description: 'Your SSH key'
    required: true
outputs:
  TIME:
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
