name: 'GitHub Pages Publish'
description: 'Publish to GitHub Pages using your SSH key'
author: 'LuisEnMarroquin'
branding:
  color: 'blue'
  icon: 'droplet'
inputs:
  BRANCH:
    description: 'Branch to move'
    default: 'gh-pages'
    required: false
  FOLDER:
    description: 'Folder to move'
    required: true
  SSHKEY:
    description: 'GitHub SSH key'
    required: true
outputs:
  TIMING:
    description: 'Time action finished'
runs:
  using: 'node12'
  main: 'dist/index.js'
