name: 'GitHub Pages Publish'
description: 'Publish to GitHub Pages using your SSH key'
author: 'LuisEnMarroquin'
inputs:
  BRANCH:
    description: 'Branch to move'
    default: 'gh-pages'
    required: false
  DELETE:
    description: 'Delete commit history'
    default: false
    required: false
  FOLDER:
    description: 'Folder to move'
    required: true
  SSHKEY:
    description: 'Your SSH key'
    required: true
outputs:
  TIMING:
    description: 'The time action ended execution'
runs:
  using: 'node12'
  main: 'dist/index.js'
