name: Testing

on:
  push:
    branches:
    - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: LuisEnMarroquin/gh-pages-publish@v2.4.3
      with:
        FOLDER: dist
        SSHKEY: ${{ secrets.SSH }}
  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: LuisEnMarroquin/gh-pages-publish@v2.4.3
      with:
        BRANCH: gh-pages-mac
        FOLDER: dist
        SSHKEY: ${{ secrets.SSH }}
  win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: LuisEnMarroquin/gh-pages-publish@v2.4.3
      with:
        BRANCH: gh-pages-win
        FOLDER: dist
        SSHKEY: ${{ secrets.SSH }}
  github:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: gh auth login --help
    - run: gh issue list
    - run: gh release create --help
