name: macOS

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: LuisEnMarroquin/gh-pages-publish@v2.4.4
      with:
        BRANCH: gh-pages-mac
        FOLDER: dist
        SSHKEY: ${{ secrets.SSH }}
