name: Testing

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get the repository
      uses: actions/checkout@v2

    - name: Get initial path
      run: ls -a

    - name: Deploy to gh-pages
      uses: LuisEnMarroquin/gh-pages-publish@v1.4
      id: hello
      with:
        BRANCH: gh-pages
        FOLDER: dist
        SSHKEY: ${{ secrets.SSH }}

    - name: Use the output from the `hello` step
      run: echo "The time was ${{ steps.hello.outputs.TIMING }}"

    - name: Git is logged in
      run: ssh -T git@github.com
