name: Testing

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get the repository
      uses: actions/checkout@v2
    - name: Deploy to gh-pages
      uses: LuisEnMarroquin/gh-pages-publish@v2.1.97
      id: hello
      with:
        FOLDER: dist
        SSHKEY: ${{ secrets.SSH }}
    - name: Use the output from the `hello` step
      run: echo "The time was ${{ steps.hello.outputs.TIMING }}"
    - name: test SSH
      run: ssh -T git@github.com || true
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: LuisEnMarroquin/gh-pages-publish@v2.1.97
      with:
        BRANCH: gh-pages-mac
        DELETE: true
        FOLDER: dist
        SSHKEY: ${{ secrets.SSH }}
  ubuntu-16:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: LuisEnMarroquin/gh-pages-publish@v2.1.97
      with:
        BRANCH: gh-pages-16
        DELETE: true
        FOLDER: dist
        SSHKEY: ${{ secrets.SSH }}
  ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: LuisEnMarroquin/gh-pages-publish@v2.1.97
      with:
        BRANCH: gh-pages-20
        DELETE: true
        FOLDER: dist
        SSHKEY: ${{ secrets.SSH }}
