name: Testing

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get the repository
      uses: actions/checkout@v2
    # Get system information
    - name: Information
      run: ls && pwd
    # Run my action
    - name: Deploy to gh-pages
      uses: LuisEnMarroquin/gh-pages-publish@v1.0
      id: hello
      with:
        SSHKEY: ${{ secrets.SSH }}
        BRANCH: gh-pages
        FOLDER: dist
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.TIME }}"
    # Show whats on home folder
    - name: Home folder
      run: cd $HOME && ls && ls -a
