name: Ubuntu

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: LuisEnMarroquin/gh-pages-publish@v2.3.4
      id: hello
      with:
        FOLDER: dist
        SSHKEY: ${{ secrets.SSH }}
    - name: Use the output from the `hello` step
      run: echo "The time was ${{ steps.hello.outputs.TIMING }}"
    - name: Test SSH connection
      run: ssh -T git@github.com || true
