name: Ubuntu

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: LuisEnMarroquin/gh-pages-publish@v2.4.3
      with:
        FOLDER: dist
        SSHKEY: ${{ secrets.SSH }}
  github:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: gh auth login --help
    - run: gh auth status || true
    - run: gh config set git_protocol ssh
