name: Windows

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: LuisEnMarroquin/gh-pages-publish@v2.4.6
        with:
          BRANCH: gh-pages-win
          FOLDER: dist
          SSHKEY: ${{ secrets.SSH }}
